export const GendersList = [
    { name: 'Disable', id: 0 },
    { name: 'Male', id: 1 },
    { name: 'Female', id: 2 },
    { name: 'Transgender', id: 3 },
    { name: 'Gender neutral', id: 4 },
    { name: 'Non-binary', id: 5 },
    { name: 'Agender', id: 6 },
    { name: 'Third gender', id: 7 },
    { name: 'Two-spirit', id: 8 }
];

export const CountriesList = [
    { name: 'Australia', id: 1 },
    { name: 'Russia', id: 2 },
    { name: 'United States', id: 3 },
    { name: 'Ukraine', id: 4 },
    { name: 'Poland', id: 5 },
    { name: 'Sweden', id: 6 },
    { name: 'China', id: 7 },
    { name: 'Japan', id: 8 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
    { name: 'Thailand', id: 9 },
];
