<template>

  <Page actionBarHidden="true">

    <ActivityIndicator :busy="isBusy"  @loaded="someMethod" class="activity-indicator" />

    <ListView for="item in items" v-if="!isBusy">

      <v-template>

        <StackLayout orientation="vertical">
          <Label :text="item.title" row="0" class="post-list-title" textWrap="true" @tap="openPage(item)"/>
        </StackLayout>

      </v-template>

    </ListView>

  </Page>

</template>

<script>

import PagesBlocks from "~/components/templates/modules/pageBuilder/PagesBlocks";

export default {

  components: {
    PagesBlocks
  },

  data() {
    return {
      isBusy: false,
      items: []
    }
  },

  created() {
    this.getData();
  },


  methods: {

    someMethod(arg) {
      this.isBusy = true;
    },

    openPage(page) {
      this.$showModal(PagesBlocks, {
        fullscreen: true,
        animated: true,
        stretched: true,
        dimAmount: 0.5
      });

      this.$root.$emit('page::open', page);

    },

    getData() {
      this.items = [];

      this.items = [
        {
          "id": 3,
          "app_id": 2,
          "template_id": null,
          "title": "third",
          "thumb": null,
          "short_content": null,
          "is_active": true,
          "created_at": null,
          "updated_at": null,
          "active_blocks": [
            {
              "id": 130,
              "page_id": 3,
              "template_id": 9,
              "order": 1,
              "is_active": true,
              "created_at": "2020-11-24 11:21:28",
              "updated_at": "2020-12-01 10:36:24",
              "s_order": 1,
              "layout": "2",
              "is_deleted": false,
              "template": {
                "id": 9,
                "app_id": 2,
                "name": "32",
                "margin": "2",
                "padding": "4",
                "created_at": "2020-09-29 16:04:13",
                "updated_at": "2020-09-29 16:04:13",
                "border_width": "auto",
                "height": "auto",
                "width": "auto",
                "color": "black",
                "bg_color": "white",
                "border_type": null,
                "border_color": null,
                "border_radius": null,
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": null,
                "style": "margin: 2;padding: 4;border-width: auto;height: auto;color: black;background-color: white;overflow:auto;text-align:left;"
              },
              "elements": [
                {
                  "id": 120,
                  "block_id": 130,
                  "template_id": 8,
                  "content": "<p>Hi my name is</p>",
                  "created_at": "2020-11-27 09:22:00",
                  "updated_at": "2020-11-27 11:48:34",
                  "type": "html",
                  "images": [],
                  "template": {
                    "id": 8,
                    "app_id": 2,
                    "name": "image template",
                    "margin": "0px",
                    "padding": "3px",
                    "created_at": "2020-09-29 15:48:10",
                    "updated_at": "2020-11-26 21:23:42",
                    "border_width": "2px",
                    "height": "250px",
                    "width": "150px",
                    "color": "#fafafa",
                    "bg_color": "#ee7c7c",
                    "border_type": null,
                    "border_color": "#c74343",
                    "border_radius": "5px",
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": "center",
                    "style": "margin: 0px;padding: 3px;border-width: 2px;border-color: #c74343;border-radius: 5px;height: 250px;color: #fafafa;background-color: #ee7c7c;overflow:auto;text-align: center;"
                  }
                }
              ]
            },
            {
              "id": 129,
              "page_id": 3,
              "template_id": 9,
              "order": 1,
              "is_active": true,
              "created_at": "2020-11-24 11:21:28",
              "updated_at": "2020-12-01 10:36:24",
              "s_order": 2,
              "layout": "2",
              "is_deleted": false,
              "template": {
                "id": 9,
                "app_id": 2,
                "name": "32",
                "margin": "2",
                "padding": "4",
                "created_at": "2020-09-29 16:04:13",
                "updated_at": "2020-09-29 16:04:13",
                "border_width": "auto",
                "height": "auto",
                "width": "auto",
                "color": "black",
                "bg_color": "white",
                "border_type": null,
                "border_color": null,
                "border_radius": null,
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": null,
                "style": "margin: 2;padding: 4;border-width: auto;height: auto;color: black;background-color: white;overflow:auto;text-align:left;"
              },
              "elements": [
                {
                  "id": 123,
                  "block_id": 129,
                  "template_id": 12,
                  "content": "<ol><li>First</li><li>Second</li></ol>",
                  "created_at": "2020-11-27 10:01:13",
                  "updated_at": "2020-11-27 10:01:13",
                  "type": "html",
                  "images": [],
                  "template": {
                    "id": 12,
                    "app_id": 2,
                    "name": "32",
                    "margin": "0px",
                    "padding": "4",
                    "created_at": "2020-09-29 16:04:24",
                    "updated_at": "2020-11-13 15:38:42",
                    "border_width": "auto",
                    "height": "100",
                    "width": "50%",
                    "color": "black",
                    "bg_color": "white",
                    "border_type": null,
                    "border_color": null,
                    "border_radius": null,
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": null,
                    "style": "margin: 0px;padding: 4;border-width: auto;height: 100;color: black;background-color: white;overflow:auto;text-align:left;"
                  }
                },
                {
                  "id": 121,
                  "block_id": 129,
                  "template_id": 12,
                  "content": "<ol><li>21</li><li>32434</li></ol>",
                  "created_at": "2020-11-27 09:23:52",
                  "updated_at": "2020-12-07 16:09:55",
                  "type": "html",
                  "images": [],
                  "template": {
                    "id": 12,
                    "app_id": 2,
                    "name": "32",
                    "margin": "0px",
                    "padding": "4",
                    "created_at": "2020-09-29 16:04:24",
                    "updated_at": "2020-11-13 15:38:42",
                    "border_width": "auto",
                    "height": "100",
                    "width": "50%",
                    "color": "black",
                    "bg_color": "white",
                    "border_type": null,
                    "border_color": null,
                    "border_radius": null,
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": null,
                    "style": "margin: 0px;padding: 4;border-width: auto;height: 100;color: black;background-color: white;overflow:auto;text-align:left;"
                  }
                },
                {
                  "id": 139,
                  "block_id": 129,
                  "template_id": 22,
                  "content": "<ol><li>fawfawfawd</li><li>agsegasfsa</li></ol>",
                  "created_at": "2020-11-30 11:33:35",
                  "updated_at": "2020-12-14 12:26:38",
                  "type": "html",
                  "images": [],
                  "template": {
                    "id": 22,
                    "app_id": 2,
                    "name": "template #1",
                    "margin": "5px 10px",
                    "padding": "3px",
                    "created_at": "2020-10-08 16:05:52",
                    "updated_at": "2020-12-07 16:32:41",
                    "border_width": "2px",
                    "height": "250px",
                    "width": "250px",
                    "color": "#ffffff",
                    "bg_color": "#35ed3b",
                    "border_type": null,
                    "border_color": null,
                    "border_radius": "5px",
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": "center",
                    "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
                  }
                },
                {
                  "id": 134,
                  "block_id": 129,
                  "template_id": 22,
                  "content": "{\"button_title\":\"Google1\",\"button_link\":\"https://www.google.com/\"}",
                  "created_at": "2020-11-29 19:22:57",
                  "updated_at": "2020-12-01 09:44:42",
                  "type": "button",
                  "images": [],
                  "template": {
                    "id": 22,
                    "app_id": 2,
                    "name": "template #1",
                    "margin": "5px 10px",
                    "padding": "3px",
                    "created_at": "2020-10-08 16:05:52",
                    "updated_at": "2020-12-07 16:32:41",
                    "border_width": "2px",
                    "height": "250px",
                    "width": "250px",
                    "color": "#ffffff",
                    "bg_color": "#35ed3b",
                    "border_type": null,
                    "border_color": null,
                    "border_radius": "5px",
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": "center",
                    "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
                  }
                }
              ]
            },
            {
              "id": 133,
              "page_id": 3,
              "template_id": 11,
              "order": 2,
              "is_active": true,
              "created_at": "2020-11-25 10:29:07",
              "updated_at": "2020-12-01 10:36:36",
              "s_order": 1,
              "layout": "4",
              "is_deleted": false,
              "template": {
                "id": 11,
                "app_id": 2,
                "name": "32",
                "margin": "2",
                "padding": "4",
                "created_at": "2020-09-29 16:04:20",
                "updated_at": "2020-09-29 16:04:20",
                "border_width": "auto",
                "height": "auto",
                "width": "auto",
                "color": "black",
                "bg_color": "white",
                "border_type": null,
                "border_color": null,
                "border_radius": null,
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": null,
                "style": "margin: 2;padding: 4;border-width: auto;height: auto;color: black;background-color: white;overflow:auto;text-align:left;"
              },
              "elements": [
                {
                  "id": 117,
                  "block_id": 133,
                  "template_id": 8,
                  "content": null,
                  "created_at": "2020-11-27 09:08:16",
                  "updated_at": "2020-11-27 09:08:16",
                  "type": "image",
                  "images": [
                    {
                      "id": 44,
                      "entity": "image",
                      "entity_id": 117,
                      "template_id": null,
                      "url_original": "/img/uploads/w-1606457296.PNG",
                      "url_medium": "/img/uploads/w-1606457296.PNG",
                      "url_small": "/img/uploads/w-1606457296.PNG",
                      "order": 1,
                      "created_at": "2020-11-27 09:08:16",
                      "updated_at": "2020-11-27 09:08:16",
                      "image_url": "http://ycms-client.loc/img/uploads/w-1606457296.PNG"
                    }
                  ],
                  "template": {
                    "id": 8,
                    "app_id": 2,
                    "name": "image template",
                    "margin": "0px",
                    "padding": "3px",
                    "created_at": "2020-09-29 15:48:10",
                    "updated_at": "2020-11-26 21:23:42",
                    "border_width": "2px",
                    "height": "250px",
                    "width": "150px",
                    "color": "#fafafa",
                    "bg_color": "#ee7c7c",
                    "border_type": null,
                    "border_color": "#c74343",
                    "border_radius": "5px",
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": "center",
                    "style": "margin: 0px;padding: 3px;border-width: 2px;border-color: #c74343;border-radius: 5px;height: 250px;color: #fafafa;background-color: #ee7c7c;overflow:auto;text-align: center;"
                  }
                }
              ]
            },
            {
              "id": 132,
              "page_id": 3,
              "template_id": 7,
              "order": 2,
              "is_active": true,
              "created_at": "2020-11-25 10:29:07",
              "updated_at": "2020-12-01 10:36:38",
              "s_order": 2,
              "layout": "4",
              "is_deleted": false,
              "template": {
                "id": 7,
                "app_id": 2,
                "name": "sk",
                "margin": "1",
                "padding": "1",
                "created_at": "2020-09-29 15:47:32",
                "updated_at": "2020-10-22 16:32:51",
                "border_width": "auto",
                "height": "auto",
                "width": "auto",
                "color": "black",
                "bg_color": "white",
                "border_type": null,
                "border_color": null,
                "border_radius": null,
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": null,
                "style": "margin: 1;padding: 1;border-width: auto;height: auto;color: black;background-color: white;overflow:auto;text-align:left;"
              },
              "elements": [
                {
                  "id": 105,
                  "block_id": 132,
                  "template_id": 8,
                  "content": "EjWqTangPiM",
                  "created_at": "2020-11-19 20:33:53",
                  "updated_at": "2020-11-25 11:50:36",
                  "type": "video",
                  "images": [],
                  "template": {
                    "id": 8,
                    "app_id": 2,
                    "name": "image template",
                    "margin": "0px",
                    "padding": "3px",
                    "created_at": "2020-09-29 15:48:10",
                    "updated_at": "2020-11-26 21:23:42",
                    "border_width": "2px",
                    "height": "250px",
                    "width": "150px",
                    "color": "#fafafa",
                    "bg_color": "#ee7c7c",
                    "border_type": null,
                    "border_color": "#c74343",
                    "border_radius": "5px",
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": "center",
                    "style": "margin: 0px;padding: 3px;border-width: 2px;border-color: #c74343;border-radius: 5px;height: 250px;color: #fafafa;background-color: #ee7c7c;overflow:auto;text-align: center;"
                  }
                }
              ]
            },
            {
              "id": 134,
              "page_id": 3,
              "template_id": 7,
              "order": 2,
              "is_active": true,
              "created_at": "2020-11-25 10:29:07",
              "updated_at": "2020-12-01 10:36:38",
              "s_order": 3,
              "layout": "4",
              "is_deleted": false,
              "template": {
                "id": 7,
                "app_id": 2,
                "name": "sk",
                "margin": "1",
                "padding": "1",
                "created_at": "2020-09-29 15:47:32",
                "updated_at": "2020-10-22 16:32:51",
                "border_width": "auto",
                "height": "auto",
                "width": "auto",
                "color": "black",
                "bg_color": "white",
                "border_type": null,
                "border_color": null,
                "border_radius": null,
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": null,
                "style": "margin: 1;padding: 1;border-width: auto;height: auto;color: black;background-color: white;overflow:auto;text-align:left;"
              },
              "elements": []
            },
            {
              "id": 135,
              "page_id": 3,
              "template_id": 6,
              "order": 2,
              "is_active": true,
              "created_at": "2020-11-25 10:29:07",
              "updated_at": "2020-11-27 08:59:01",
              "s_order": 4,
              "layout": "4",
              "is_deleted": false,
              "template": {
                "id": 6,
                "app_id": 2,
                "name": "newer",
                "margin": "auto",
                "padding": "0px",
                "created_at": "2020-09-29 15:47:32",
                "updated_at": "2020-09-29 15:47:32",
                "border_width": "1px solid lightgreen",
                "height": "auto",
                "width": "10%",
                "color": "black",
                "bg_color": "white",
                "border_type": null,
                "border_color": null,
                "border_radius": null,
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": null,
                "style": "margin: auto;padding: 0px;border-width: 1px solid lightgreen;height: auto;color: black;background-color: white;overflow:auto;text-align:left;"
              },
              "elements": [
                {
                  "id": 124,
                  "block_id": 135,
                  "template_id": 22,
                  "content": "<p><strong>Some text</strong></p>",
                  "created_at": "2020-11-27 10:34:59",
                  "updated_at": "2020-11-27 10:34:59",
                  "type": "html",
                  "images": [],
                  "template": {
                    "id": 22,
                    "app_id": 2,
                    "name": "template #1",
                    "margin": "5px 10px",
                    "padding": "3px",
                    "created_at": "2020-10-08 16:05:52",
                    "updated_at": "2020-12-07 16:32:41",
                    "border_width": "2px",
                    "height": "250px",
                    "width": "250px",
                    "color": "#ffffff",
                    "bg_color": "#35ed3b",
                    "border_type": null,
                    "border_color": null,
                    "border_radius": "5px",
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": "center",
                    "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
                  }
                }
              ]
            },
            {
              "id": 131,
              "page_id": 3,
              "template_id": 13,
              "order": 4,
              "is_active": true,
              "created_at": "2020-11-24 23:40:49",
              "updated_at": "2020-11-26 18:05:03",
              "s_order": 1,
              "layout": "1",
              "is_deleted": false,
              "template": {
                "id": 13,
                "app_id": 2,
                "name": "newset",
                "margin": "none",
                "padding": "0px",
                "created_at": "2020-09-30 09:03:39",
                "updated_at": "2020-11-17 11:13:08",
                "border_width": "0px",
                "height": "200px",
                "width": "100%",
                "color": "black",
                "bg_color": "white",
                "border_type": null,
                "border_color": null,
                "border_radius": null,
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": null,
                "style": "margin: none;padding: 0px;border-width: 0px;height: 200px;color: black;background-color: white;overflow:auto;text-align:left;"
              },
              "elements": [
                {
                  "id": 109,
                  "block_id": 131,
                  "template_id": 25,
                  "content": "{\"address\":\"улица Айтеке Би 152, Алматы, Казахстан\",\"lat\":43.2574328,\"lng\":76.9334329}",
                  "created_at": "2020-11-26 10:15:13",
                  "updated_at": "2020-11-26 10:15:13",
                  "type": "map",
                  "images": [],
                  "template": {
                    "id": 25,
                    "app_id": 2,
                    "name": "map template",
                    "margin": "0px",
                    "padding": "0px",
                    "created_at": "2020-10-09 08:16:25",
                    "updated_at": "2020-11-26 22:34:06",
                    "border_width": "1px solid pink",
                    "height": "150px",
                    "width": "200px",
                    "color": "black",
                    "bg_color": "white",
                    "border_type": null,
                    "border_color": null,
                    "border_radius": null,
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": "right",
                    "style": "margin: 0px;padding: 0px;border-width: 1px solid pink;height: 150px;color: black;background-color: white;overflow:auto;text-align: right;"
                  }
                },
                {
                  "id": 133,
                  "block_id": 131,
                  "template_id": 8,
                  "content": null,
                  "created_at": "2020-11-27 09:22:00",
                  "updated_at": "2020-11-27 11:35:03",
                  "type": "image",
                  "images": [
                    {
                      "id": 58,
                      "entity": "image",
                      "entity_id": 133,
                      "template_id": null,
                      "url_original": "/img/uploads/Capture-1606466938.PNG",
                      "url_medium": "/img/uploads/Capture-1606466938.PNG",
                      "url_small": "/img/uploads/Capture-1606466938.PNG",
                      "order": 1,
                      "created_at": "2020-11-27 11:48:58",
                      "updated_at": "2020-11-27 11:48:58",
                      "image_url": "http://ycms-client.loc/img/uploads/Capture-1606466938.PNG"
                    }
                  ],
                  "template": {
                    "id": 8,
                    "app_id": 2,
                    "name": "image template",
                    "margin": "0px",
                    "padding": "3px",
                    "created_at": "2020-09-29 15:48:10",
                    "updated_at": "2020-11-26 21:23:42",
                    "border_width": "2px",
                    "height": "250px",
                    "width": "150px",
                    "color": "#fafafa",
                    "bg_color": "#ee7c7c",
                    "border_type": null,
                    "border_color": "#c74343",
                    "border_radius": "5px",
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": "center",
                    "style": "margin: 0px;padding: 3px;border-width: 2px;border-color: #c74343;border-radius: 5px;height: 250px;color: #fafafa;background-color: #ee7c7c;overflow:auto;text-align: center;"
                  }
                }
              ]
            },
            {
              "id": 145,
              "page_id": 3,
              "template_id": 22,
              "order": 8,
              "is_active": true,
              "created_at": "2020-11-26 17:22:13",
              "updated_at": "2020-11-27 08:52:44",
              "s_order": 1,
              "layout": "3-4",
              "is_deleted": false,
              "template": {
                "id": 22,
                "app_id": 2,
                "name": "template #1",
                "margin": "5px 10px",
                "padding": "3px",
                "created_at": "2020-10-08 16:05:52",
                "updated_at": "2020-12-07 16:32:41",
                "border_width": "2px",
                "height": "250px",
                "width": "250px",
                "color": "#ffffff",
                "bg_color": "#35ed3b",
                "border_type": null,
                "border_color": null,
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
              },
              "elements": [
                {
                  "id": 113,
                  "block_id": 145,
                  "template_id": 25,
                  "content": "{\"address\":\"Шолаккорган, Казахстан\",\"lat\":43.7649257,\"lng\":69.17952439999999}",
                  "created_at": "2020-11-26 21:22:33",
                  "updated_at": "2020-11-26 21:22:33",
                  "type": "map",
                  "images": [],
                  "template": {
                    "id": 25,
                    "app_id": 2,
                    "name": "map template",
                    "margin": "0px",
                    "padding": "0px",
                    "created_at": "2020-10-09 08:16:25",
                    "updated_at": "2020-11-26 22:34:06",
                    "border_width": "1px solid pink",
                    "height": "150px",
                    "width": "200px",
                    "color": "black",
                    "bg_color": "white",
                    "border_type": null,
                    "border_color": null,
                    "border_radius": null,
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": "right",
                    "style": "margin: 0px;padding: 0px;border-width: 1px solid pink;height: 150px;color: black;background-color: white;overflow:auto;text-align: right;"
                  }
                }
              ]
            },
            {
              "id": 146,
              "page_id": 3,
              "template_id": 22,
              "order": 8,
              "is_active": true,
              "created_at": "2020-11-26 17:22:13",
              "updated_at": "2020-11-27 08:52:44",
              "s_order": 2,
              "layout": "1-4",
              "is_deleted": false,
              "template": {
                "id": 22,
                "app_id": 2,
                "name": "template #1",
                "margin": "5px 10px",
                "padding": "3px",
                "created_at": "2020-10-08 16:05:52",
                "updated_at": "2020-12-07 16:32:41",
                "border_width": "2px",
                "height": "250px",
                "width": "250px",
                "color": "#ffffff",
                "bg_color": "#35ed3b",
                "border_type": null,
                "border_color": null,
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
              },
              "elements": [
                {
                  "id": 114,
                  "block_id": 146,
                  "template_id": 8,
                  "content": null,
                  "created_at": "2020-11-26 21:23:12",
                  "updated_at": "2020-11-26 21:23:12",
                  "type": "image",
                  "images": [
                    {
                      "id": 43,
                      "entity": "image",
                      "entity_id": 114,
                      "template_id": null,
                      "url_original": "/img/uploads/510572389-1606414992.jpeg",
                      "url_medium": "/img/uploads/510572389-1606414992.jpeg",
                      "url_small": "/img/uploads/510572389-1606414992.jpeg",
                      "order": 1,
                      "created_at": "2020-11-26 21:23:12",
                      "updated_at": "2020-11-26 21:23:12",
                      "image_url": "http://ycms-client.loc/img/uploads/510572389-1606414992.jpeg"
                    }
                  ],
                  "template": {
                    "id": 8,
                    "app_id": 2,
                    "name": "image template",
                    "margin": "0px",
                    "padding": "3px",
                    "created_at": "2020-09-29 15:48:10",
                    "updated_at": "2020-11-26 21:23:42",
                    "border_width": "2px",
                    "height": "250px",
                    "width": "150px",
                    "color": "#fafafa",
                    "bg_color": "#ee7c7c",
                    "border_type": null,
                    "border_color": "#c74343",
                    "border_radius": "5px",
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": "center",
                    "style": "margin: 0px;padding: 3px;border-width: 2px;border-color: #c74343;border-radius: 5px;height: 250px;color: #fafafa;background-color: #ee7c7c;overflow:auto;text-align: center;"
                  }
                }
              ]
            },
            {
              "id": 149,
              "page_id": 3,
              "template_id": 22,
              "order": 10,
              "is_active": true,
              "created_at": "2020-11-26 17:22:53",
              "updated_at": "2020-12-10 15:04:18",
              "s_order": 1,
              "layout": "1-3",
              "is_deleted": false,
              "template": {
                "id": 22,
                "app_id": 2,
                "name": "template #1",
                "margin": "5px 10px",
                "padding": "3px",
                "created_at": "2020-10-08 16:05:52",
                "updated_at": "2020-12-07 16:32:41",
                "border_width": "2px",
                "height": "250px",
                "width": "250px",
                "color": "#ffffff",
                "bg_color": "#35ed3b",
                "border_type": null,
                "border_color": null,
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
              },
              "elements": []
            },
            {
              "id": 148,
              "page_id": 3,
              "template_id": 22,
              "order": 10,
              "is_active": true,
              "created_at": "2020-11-26 17:22:53",
              "updated_at": "2020-12-10 15:04:18",
              "s_order": 2,
              "layout": "2-3",
              "is_deleted": false,
              "template": {
                "id": 22,
                "app_id": 2,
                "name": "template #1",
                "margin": "5px 10px",
                "padding": "3px",
                "created_at": "2020-10-08 16:05:52",
                "updated_at": "2020-12-07 16:32:41",
                "border_width": "2px",
                "height": "250px",
                "width": "250px",
                "color": "#ffffff",
                "bg_color": "#35ed3b",
                "border_type": null,
                "border_color": null,
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
              },
              "elements": [
                {
                  "id": 115,
                  "block_id": 148,
                  "template_id": 45,
                  "content": "EjWqTangPiM",
                  "created_at": "2020-11-27 08:52:18",
                  "updated_at": "2020-11-27 08:52:18",
                  "type": "video",
                  "images": [],
                  "template": {
                    "id": 45,
                    "app_id": 2,
                    "name": "slider template",
                    "margin": "0px",
                    "padding": "0px",
                    "created_at": "2020-11-17 12:10:52",
                    "updated_at": "2020-11-26 21:21:42",
                    "border_width": "2px",
                    "height": "170px",
                    "width": "300px",
                    "color": "#ce2c2c",
                    "bg_color": "#ffffff",
                    "border_type": "dashed",
                    "border_color": "#14bd3e",
                    "border_radius": null,
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": null,
                    "style": "margin: 0px;padding: 0px;border-width: 2px;border-style: dashed;border-color: #14bd3e;height: 170px;color: #ce2c2c;background-color: #ffffff;overflow:auto;text-align:left;"
                  }
                }
              ]
            },
            {
              "id": 154,
              "page_id": 3,
              "template_id": 22,
              "order": 12,
              "is_active": true,
              "created_at": "2020-11-27 08:58:51",
              "updated_at": "2020-12-01 09:39:05",
              "s_order": 1,
              "layout": "4",
              "is_deleted": false,
              "template": {
                "id": 22,
                "app_id": 2,
                "name": "template #1",
                "margin": "5px 10px",
                "padding": "3px",
                "created_at": "2020-10-08 16:05:52",
                "updated_at": "2020-12-07 16:32:41",
                "border_width": "2px",
                "height": "250px",
                "width": "250px",
                "color": "#ffffff",
                "bg_color": "#35ed3b",
                "border_type": null,
                "border_color": null,
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
              },
              "elements": []
            },
            {
              "id": 155,
              "page_id": 3,
              "template_id": 22,
              "order": 12,
              "is_active": true,
              "created_at": "2020-11-27 08:58:51",
              "updated_at": "2020-12-01 09:39:05",
              "s_order": 2,
              "layout": "4",
              "is_deleted": false,
              "template": {
                "id": 22,
                "app_id": 2,
                "name": "template #1",
                "margin": "5px 10px",
                "padding": "3px",
                "created_at": "2020-10-08 16:05:52",
                "updated_at": "2020-12-07 16:32:41",
                "border_width": "2px",
                "height": "250px",
                "width": "250px",
                "color": "#ffffff",
                "bg_color": "#35ed3b",
                "border_type": null,
                "border_color": null,
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
              },
              "elements": []
            },
            {
              "id": 156,
              "page_id": 3,
              "template_id": 22,
              "order": 12,
              "is_active": true,
              "created_at": "2020-11-27 08:58:51",
              "updated_at": "2020-12-01 09:39:05",
              "s_order": 3,
              "layout": "4",
              "is_deleted": false,
              "template": {
                "id": 22,
                "app_id": 2,
                "name": "template #1",
                "margin": "5px 10px",
                "padding": "3px",
                "created_at": "2020-10-08 16:05:52",
                "updated_at": "2020-12-07 16:32:41",
                "border_width": "2px",
                "height": "250px",
                "width": "250px",
                "color": "#ffffff",
                "bg_color": "#35ed3b",
                "border_type": null,
                "border_color": null,
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
              },
              "elements": []
            },
            {
              "id": 157,
              "page_id": 3,
              "template_id": 22,
              "order": 12,
              "is_active": true,
              "created_at": "2020-11-27 08:58:51",
              "updated_at": "2020-12-01 09:39:05",
              "s_order": 4,
              "layout": "4",
              "is_deleted": false,
              "template": {
                "id": 22,
                "app_id": 2,
                "name": "template #1",
                "margin": "5px 10px",
                "padding": "3px",
                "created_at": "2020-10-08 16:05:52",
                "updated_at": "2020-12-07 16:32:41",
                "border_width": "2px",
                "height": "250px",
                "width": "250px",
                "color": "#ffffff",
                "bg_color": "#35ed3b",
                "border_type": null,
                "border_color": null,
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
              },
              "elements": []
            },
            {
              "id": 125,
              "page_id": 3,
              "template_id": 22,
              "order": 13,
              "is_active": true,
              "created_at": "2020-11-13 15:21:44",
              "updated_at": "2020-12-01 09:39:05",
              "s_order": 1,
              "layout": "2",
              "is_deleted": false,
              "template": {
                "id": 22,
                "app_id": 2,
                "name": "template #1",
                "margin": "5px 10px",
                "padding": "3px",
                "created_at": "2020-10-08 16:05:52",
                "updated_at": "2020-12-07 16:32:41",
                "border_width": "2px",
                "height": "250px",
                "width": "250px",
                "color": "#ffffff",
                "bg_color": "#35ed3b",
                "border_type": null,
                "border_color": null,
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
              },
              "elements": [
                {
                  "id": 80,
                  "block_id": 125,
                  "template_id": 13,
                  "content": null,
                  "created_at": "2020-11-16 14:33:02",
                  "updated_at": "2020-11-16 14:33:02",
                  "type": "slider",
                  "images": [
                    {
                      "id": 6,
                      "entity": "slider",
                      "entity_id": 80,
                      "template_id": null,
                      "url_original": "/img/uploads/Capture - Copy-1605526383.PNG",
                      "url_medium": "/img/uploads/Capture - Copy-1605526383.PNG",
                      "url_small": "/img/uploads/Capture - Copy-1605526383.PNG",
                      "order": 1,
                      "created_at": "2020-11-16 14:33:03",
                      "updated_at": "2020-11-16 14:33:03",
                      "image_url": "http://ycms-client.loc/img/uploads/Capture - Copy-1605526383.PNG"
                    },
                    {
                      "id": 26,
                      "entity": "slider",
                      "entity_id": 80,
                      "template_id": null,
                      "url_original": "/img/uploads/Capture - Copy-1605622694.PNG",
                      "url_medium": "/img/uploads/Capture - Copy-1605622694.PNG",
                      "url_small": "/img/uploads/Capture - Copy-1605622694.PNG",
                      "order": 3,
                      "created_at": "2020-11-17 17:18:14",
                      "updated_at": "2020-11-17 17:18:14",
                      "image_url": "http://ycms-client.loc/img/uploads/Capture - Copy-1605622694.PNG"
                    },
                    {
                      "id": 27,
                      "entity": "slider",
                      "entity_id": 80,
                      "template_id": null,
                      "url_original": "/img/uploads/Capture-1605622694.PNG",
                      "url_medium": "/img/uploads/Capture-1605622694.PNG",
                      "url_small": "/img/uploads/Capture-1605622694.PNG",
                      "order": 4,
                      "created_at": "2020-11-17 17:18:14",
                      "updated_at": "2020-11-17 17:18:14",
                      "image_url": "http://ycms-client.loc/img/uploads/Capture-1605622694.PNG"
                    },
                    {
                      "id": 28,
                      "entity": "slider",
                      "entity_id": 80,
                      "template_id": null,
                      "url_original": "/img/uploads/w - Copy-1605622694.PNG",
                      "url_medium": "/img/uploads/w - Copy-1605622694.PNG",
                      "url_small": "/img/uploads/w - Copy-1605622694.PNG",
                      "order": 5,
                      "created_at": "2020-11-17 17:18:14",
                      "updated_at": "2020-11-17 17:18:14",
                      "image_url": "http://ycms-client.loc/img/uploads/w - Copy-1605622694.PNG"
                    },
                    {
                      "id": 29,
                      "entity": "slider",
                      "entity_id": 80,
                      "template_id": null,
                      "url_original": "/img/uploads/w-1605622694.PNG",
                      "url_medium": "/img/uploads/w-1605622694.PNG",
                      "url_small": "/img/uploads/w-1605622694.PNG",
                      "order": 6,
                      "created_at": "2020-11-17 17:18:14",
                      "updated_at": "2020-11-17 17:18:14",
                      "image_url": "http://ycms-client.loc/img/uploads/w-1605622694.PNG"
                    },
                    {
                      "id": 30,
                      "entity": "slider",
                      "entity_id": 80,
                      "template_id": null,
                      "url_original": "/img/uploads/Снимок-1605622694.PNG",
                      "url_medium": "/img/uploads/Снимок-1605622694.PNG",
                      "url_small": "/img/uploads/Снимок-1605622694.PNG",
                      "order": 7,
                      "created_at": "2020-11-17 17:18:14",
                      "updated_at": "2020-11-17 17:18:14",
                      "image_url": "http://ycms-client.loc/img/uploads/Снимок-1605622694.PNG"
                    }
                  ],
                  "template": {
                    "id": 13,
                    "app_id": 2,
                    "name": "newset",
                    "margin": "none",
                    "padding": "0px",
                    "created_at": "2020-09-30 09:03:39",
                    "updated_at": "2020-11-17 11:13:08",
                    "border_width": "0px",
                    "height": "200px",
                    "width": "100%",
                    "color": "black",
                    "bg_color": "white",
                    "border_type": null,
                    "border_color": null,
                    "border_radius": null,
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": null,
                    "style": "margin: none;padding: 0px;border-width: 0px;height: 200px;color: black;background-color: white;overflow:auto;text-align:left;"
                  }
                }
              ]
            },
            {
              "id": 126,
              "page_id": 3,
              "template_id": 22,
              "order": 13,
              "is_active": true,
              "created_at": "2020-11-13 15:21:44",
              "updated_at": "2020-12-01 09:39:05",
              "s_order": 2,
              "layout": "2",
              "is_deleted": false,
              "template": {
                "id": 22,
                "app_id": 2,
                "name": "template #1",
                "margin": "5px 10px",
                "padding": "3px",
                "created_at": "2020-10-08 16:05:52",
                "updated_at": "2020-12-07 16:32:41",
                "border_width": "2px",
                "height": "250px",
                "width": "250px",
                "color": "#ffffff",
                "bg_color": "#35ed3b",
                "border_type": null,
                "border_color": null,
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
              },
              "elements": [
                {
                  "id": 75,
                  "block_id": 126,
                  "template_id": 9,
                  "content": null,
                  "created_at": "2020-11-16 13:47:00",
                  "updated_at": "2020-11-16 13:47:00",
                  "type": "image",
                  "images": [],
                  "template": {
                    "id": 9,
                    "app_id": 2,
                    "name": "32",
                    "margin": "2",
                    "padding": "4",
                    "created_at": "2020-09-29 16:04:13",
                    "updated_at": "2020-09-29 16:04:13",
                    "border_width": "auto",
                    "height": "auto",
                    "width": "auto",
                    "color": "black",
                    "bg_color": "white",
                    "border_type": null,
                    "border_color": null,
                    "border_radius": null,
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": null,
                    "style": "margin: 2;padding: 4;border-width: auto;height: auto;color: black;background-color: white;overflow:auto;text-align:left;"
                  }
                },
                {
                  "id": 132,
                  "block_id": 126,
                  "template_id": 22,
                  "content": "<ol><li>fe</li><li>sg</li></ol>",
                  "created_at": "2020-11-27 10:48:53",
                  "updated_at": "2020-11-27 10:48:53",
                  "type": "html",
                  "images": [],
                  "template": {
                    "id": 22,
                    "app_id": 2,
                    "name": "template #1",
                    "margin": "5px 10px",
                    "padding": "3px",
                    "created_at": "2020-10-08 16:05:52",
                    "updated_at": "2020-12-07 16:32:41",
                    "border_width": "2px",
                    "height": "250px",
                    "width": "250px",
                    "color": "#ffffff",
                    "bg_color": "#35ed3b",
                    "border_type": null,
                    "border_color": null,
                    "border_radius": "5px",
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": "center",
                    "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
                  }
                }
              ]
            },
            {
              "id": 158,
              "page_id": 3,
              "template_id": 22,
              "order": 14,
              "is_active": true,
              "created_at": "2020-11-28 21:18:59",
              "updated_at": "2020-12-01 09:39:05",
              "s_order": 1,
              "layout": "4",
              "is_deleted": false,
              "template": {
                "id": 22,
                "app_id": 2,
                "name": "template #1",
                "margin": "5px 10px",
                "padding": "3px",
                "created_at": "2020-10-08 16:05:52",
                "updated_at": "2020-12-07 16:32:41",
                "border_width": "2px",
                "height": "250px",
                "width": "250px",
                "color": "#ffffff",
                "bg_color": "#35ed3b",
                "border_type": null,
                "border_color": null,
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
              },
              "elements": []
            },
            {
              "id": 159,
              "page_id": 3,
              "template_id": 22,
              "order": 14,
              "is_active": true,
              "created_at": "2020-11-28 21:18:59",
              "updated_at": "2020-12-01 09:39:05",
              "s_order": 2,
              "layout": "4",
              "is_deleted": false,
              "template": {
                "id": 22,
                "app_id": 2,
                "name": "template #1",
                "margin": "5px 10px",
                "padding": "3px",
                "created_at": "2020-10-08 16:05:52",
                "updated_at": "2020-12-07 16:32:41",
                "border_width": "2px",
                "height": "250px",
                "width": "250px",
                "color": "#ffffff",
                "bg_color": "#35ed3b",
                "border_type": null,
                "border_color": null,
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
              },
              "elements": []
            },
            {
              "id": 160,
              "page_id": 3,
              "template_id": 22,
              "order": 14,
              "is_active": true,
              "created_at": "2020-11-28 21:18:59",
              "updated_at": "2020-12-01 09:39:05",
              "s_order": 3,
              "layout": "4",
              "is_deleted": false,
              "template": {
                "id": 22,
                "app_id": 2,
                "name": "template #1",
                "margin": "5px 10px",
                "padding": "3px",
                "created_at": "2020-10-08 16:05:52",
                "updated_at": "2020-12-07 16:32:41",
                "border_width": "2px",
                "height": "250px",
                "width": "250px",
                "color": "#ffffff",
                "bg_color": "#35ed3b",
                "border_type": null,
                "border_color": null,
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
              },
              "elements": []
            },
            {
              "id": 161,
              "page_id": 3,
              "template_id": 22,
              "order": 14,
              "is_active": true,
              "created_at": "2020-11-28 21:18:59",
              "updated_at": "2020-12-01 09:39:05",
              "s_order": 4,
              "layout": "4",
              "is_deleted": false,
              "template": {
                "id": 22,
                "app_id": 2,
                "name": "template #1",
                "margin": "5px 10px",
                "padding": "3px",
                "created_at": "2020-10-08 16:05:52",
                "updated_at": "2020-12-07 16:32:41",
                "border_width": "2px",
                "height": "250px",
                "width": "250px",
                "color": "#ffffff",
                "bg_color": "#35ed3b",
                "border_type": null,
                "border_color": null,
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
              },
              "elements": []
            },
            {
              "id": 153,
              "page_id": 3,
              "template_id": 22,
              "order": 15,
              "is_active": true,
              "created_at": "2020-11-27 08:58:14",
              "updated_at": "2020-12-01 09:39:21",
              "s_order": 1,
              "layout": "1",
              "is_deleted": false,
              "template": {
                "id": 22,
                "app_id": 2,
                "name": "template #1",
                "margin": "5px 10px",
                "padding": "3px",
                "created_at": "2020-10-08 16:05:52",
                "updated_at": "2020-12-07 16:32:41",
                "border_width": "2px",
                "height": "250px",
                "width": "250px",
                "color": "#ffffff",
                "bg_color": "#35ed3b",
                "border_type": null,
                "border_color": null,
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
              },
              "elements": [
                {
                  "id": 142,
                  "block_id": 153,
                  "template_id": 25,
                  "content": "{\"address\":\"Mountain View, Калифорния, США\",\"lat\":37.3860517,\"lng\":-122.0838511}",
                  "created_at": "2020-12-01 09:42:29",
                  "updated_at": "2020-12-01 09:42:29",
                  "type": "map",
                  "images": [],
                  "template": {
                    "id": 25,
                    "app_id": 2,
                    "name": "map template",
                    "margin": "0px",
                    "padding": "0px",
                    "created_at": "2020-10-09 08:16:25",
                    "updated_at": "2020-11-26 22:34:06",
                    "border_width": "1px solid pink",
                    "height": "150px",
                    "width": "200px",
                    "color": "black",
                    "bg_color": "white",
                    "border_type": null,
                    "border_color": null,
                    "border_radius": null,
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": "right",
                    "style": "margin: 0px;padding: 0px;border-width: 1px solid pink;height: 150px;color: black;background-color: white;overflow:auto;text-align: right;"
                  }
                }
              ]
            }
          ]
        },
        {
          "id": 5,
          "app_id": 2,
          "template_id": null,
          "title": "last",
          "thumb": null,
          "short_content": null,
          "is_active": true,
          "created_at": "2020-09-15 08:56:35",
          "updated_at": "2020-09-15 08:56:35",
          "active_blocks": [
            {
              "id": 168,
              "page_id": 5,
              "template_id": null,
              "order": 1,
              "is_active": true,
              "created_at": "2020-11-30 13:05:18",
              "updated_at": "2020-11-30 13:05:18",
              "s_order": 1,
              "layout": "1-4",
              "is_deleted": false,
              "template": null,
              "elements": []
            },
            {
              "id": 169,
              "page_id": 5,
              "template_id": null,
              "order": 1,
              "is_active": true,
              "created_at": "2020-11-30 13:05:18",
              "updated_at": "2020-11-30 13:05:18",
              "s_order": 2,
              "layout": "3-4",
              "is_deleted": false,
              "template": null,
              "elements": []
            },
            {
              "id": 170,
              "page_id": 5,
              "template_id": null,
              "order": 2,
              "is_active": true,
              "created_at": "2020-11-30 13:06:56",
              "updated_at": "2020-11-30 13:06:56",
              "s_order": 1,
              "layout": "3",
              "is_deleted": false,
              "template": null,
              "elements": []
            },
            {
              "id": 171,
              "page_id": 5,
              "template_id": null,
              "order": 2,
              "is_active": true,
              "created_at": "2020-11-30 13:06:56",
              "updated_at": "2020-11-30 13:06:56",
              "s_order": 2,
              "layout": "3",
              "is_deleted": false,
              "template": null,
              "elements": [
                {
                  "id": 140,
                  "block_id": 171,
                  "template_id": null,
                  "content": null,
                  "created_at": "2020-11-30 13:10:53",
                  "updated_at": "2020-11-30 13:10:53",
                  "type": "image",
                  "images": [
                    {
                      "id": 63,
                      "entity": "image",
                      "entity_id": 140,
                      "template_id": null,
                      "url_original": "/img/uploads/Фото в ц-1606731053.png",
                      "url_medium": "/img/uploads/Фото в ц-1606731053.png",
                      "url_small": "/img/uploads/Фото в ц-1606731053.png",
                      "order": 1,
                      "created_at": "2020-11-30 13:10:53",
                      "updated_at": "2020-11-30 13:10:53",
                      "image_url": "http://ycms-client.loc/img/uploads/Фото в ц-1606731053.png"
                    }
                  ],
                  "template": null
                }
              ]
            },
            {
              "id": 172,
              "page_id": 5,
              "template_id": null,
              "order": 2,
              "is_active": true,
              "created_at": "2020-11-30 13:06:56",
              "updated_at": "2020-11-30 13:06:56",
              "s_order": 3,
              "layout": "3",
              "is_deleted": false,
              "template": null,
              "elements": []
            }
          ]
        },
        {
          "id": 11,
          "app_id": 2,
          "template_id": null,
          "title": "some",
          "thumb": null,
          "short_content": null,
          "is_active": true,
          "created_at": "2020-11-24 11:11:02",
          "updated_at": "2020-11-24 11:11:02",
          "active_blocks": []
        },
        {
          "id": 12,
          "app_id": 2,
          "template_id": null,
          "title": "Products",
          "thumb": null,
          "short_content": null,
          "is_active": true,
          "created_at": "2020-12-02 15:35:32",
          "updated_at": "2020-12-02 15:35:32",
          "active_blocks": [
            {
              "id": 175,
              "page_id": 12,
              "template_id": 22,
              "order": 1,
              "is_active": true,
              "created_at": "2020-12-02 15:36:00",
              "updated_at": "2020-12-02 15:36:00",
              "s_order": 1,
              "layout": "1-4",
              "is_deleted": false,
              "template": {
                "id": 22,
                "app_id": 2,
                "name": "template #1",
                "margin": "5px 10px",
                "padding": "3px",
                "created_at": "2020-10-08 16:05:52",
                "updated_at": "2020-12-07 16:32:41",
                "border_width": "2px",
                "height": "250px",
                "width": "250px",
                "color": "#ffffff",
                "bg_color": "#35ed3b",
                "border_type": null,
                "border_color": null,
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
              },
              "elements": []
            },
            {
              "id": 176,
              "page_id": 12,
              "template_id": 22,
              "order": 1,
              "is_active": true,
              "created_at": "2020-12-02 15:36:00",
              "updated_at": "2020-12-02 15:36:00",
              "s_order": 2,
              "layout": "3-4",
              "is_deleted": false,
              "template": {
                "id": 22,
                "app_id": 2,
                "name": "template #1",
                "margin": "5px 10px",
                "padding": "3px",
                "created_at": "2020-10-08 16:05:52",
                "updated_at": "2020-12-07 16:32:41",
                "border_width": "2px",
                "height": "250px",
                "width": "250px",
                "color": "#ffffff",
                "bg_color": "#35ed3b",
                "border_type": null,
                "border_color": null,
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 5px 10px;padding: 3px;border-width: 2px;border-radius: 5px;height: 250px;color: #ffffff;background-color: #35ed3b;overflow:auto;text-align: center;"
              },
              "elements": [
                {
                  "id": 143,
                  "block_id": 176,
                  "template_id": 25,
                  "content": "{\"address\":\"Moscow, Россия\",\"lat\":55.755826,\"lng\":37.6172999}",
                  "created_at": "2020-12-02 15:36:44",
                  "updated_at": "2020-12-02 15:36:44",
                  "type": "map",
                  "images": [],
                  "template": {
                    "id": 25,
                    "app_id": 2,
                    "name": "map template",
                    "margin": "0px",
                    "padding": "0px",
                    "created_at": "2020-10-09 08:16:25",
                    "updated_at": "2020-11-26 22:34:06",
                    "border_width": "1px solid pink",
                    "height": "150px",
                    "width": "200px",
                    "color": "black",
                    "bg_color": "white",
                    "border_type": null,
                    "border_color": null,
                    "border_radius": null,
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": "right",
                    "style": "margin: 0px;padding: 0px;border-width: 1px solid pink;height: 150px;color: black;background-color: white;overflow:auto;text-align: right;"
                  }
                }
              ]
            },
            {
              "id": 177,
              "page_id": 12,
              "template_id": 8,
              "order": 2,
              "is_active": true,
              "created_at": "2020-12-02 15:36:07",
              "updated_at": "2020-12-02 15:36:07",
              "s_order": 1,
              "layout": "4",
              "is_deleted": false,
              "template": {
                "id": 8,
                "app_id": 2,
                "name": "image template",
                "margin": "0px",
                "padding": "3px",
                "created_at": "2020-09-29 15:48:10",
                "updated_at": "2020-11-26 21:23:42",
                "border_width": "2px",
                "height": "250px",
                "width": "150px",
                "color": "#fafafa",
                "bg_color": "#ee7c7c",
                "border_type": null,
                "border_color": "#c74343",
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 0px;padding: 3px;border-width: 2px;border-color: #c74343;border-radius: 5px;height: 250px;color: #fafafa;background-color: #ee7c7c;overflow:auto;text-align: center;"
              },
              "elements": []
            },
            {
              "id": 178,
              "page_id": 12,
              "template_id": 8,
              "order": 2,
              "is_active": true,
              "created_at": "2020-12-02 15:36:07",
              "updated_at": "2020-12-02 15:36:07",
              "s_order": 2,
              "layout": "4",
              "is_deleted": false,
              "template": {
                "id": 8,
                "app_id": 2,
                "name": "image template",
                "margin": "0px",
                "padding": "3px",
                "created_at": "2020-09-29 15:48:10",
                "updated_at": "2020-11-26 21:23:42",
                "border_width": "2px",
                "height": "250px",
                "width": "150px",
                "color": "#fafafa",
                "bg_color": "#ee7c7c",
                "border_type": null,
                "border_color": "#c74343",
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 0px;padding: 3px;border-width: 2px;border-color: #c74343;border-radius: 5px;height: 250px;color: #fafafa;background-color: #ee7c7c;overflow:auto;text-align: center;"
              },
              "elements": []
            },
            {
              "id": 179,
              "page_id": 12,
              "template_id": 8,
              "order": 2,
              "is_active": true,
              "created_at": "2020-12-02 15:36:07",
              "updated_at": "2020-12-02 15:36:07",
              "s_order": 3,
              "layout": "4",
              "is_deleted": false,
              "template": {
                "id": 8,
                "app_id": 2,
                "name": "image template",
                "margin": "0px",
                "padding": "3px",
                "created_at": "2020-09-29 15:48:10",
                "updated_at": "2020-11-26 21:23:42",
                "border_width": "2px",
                "height": "250px",
                "width": "150px",
                "color": "#fafafa",
                "bg_color": "#ee7c7c",
                "border_type": null,
                "border_color": "#c74343",
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 0px;padding: 3px;border-width: 2px;border-color: #c74343;border-radius: 5px;height: 250px;color: #fafafa;background-color: #ee7c7c;overflow:auto;text-align: center;"
              },
              "elements": []
            },
            {
              "id": 180,
              "page_id": 12,
              "template_id": 8,
              "order": 2,
              "is_active": true,
              "created_at": "2020-12-02 15:36:07",
              "updated_at": "2020-12-02 15:36:07",
              "s_order": 4,
              "layout": "4",
              "is_deleted": false,
              "template": {
                "id": 8,
                "app_id": 2,
                "name": "image template",
                "margin": "0px",
                "padding": "3px",
                "created_at": "2020-09-29 15:48:10",
                "updated_at": "2020-11-26 21:23:42",
                "border_width": "2px",
                "height": "250px",
                "width": "150px",
                "color": "#fafafa",
                "bg_color": "#ee7c7c",
                "border_type": null,
                "border_color": "#c74343",
                "border_radius": "5px",
                "text_shadow": null,
                "box_shadow": null,
                "overflow": null,
                "text_align": "center",
                "style": "margin: 0px;padding: 3px;border-width: 2px;border-color: #c74343;border-radius: 5px;height: 250px;color: #fafafa;background-color: #ee7c7c;overflow:auto;text-align: center;"
              },
              "elements": []
            },
            {
              "id": 181,
              "page_id": 12,
              "template_id": null,
              "order": 3,
              "is_active": true,
              "created_at": "2020-12-02 15:37:11",
              "updated_at": "2020-12-02 15:37:11",
              "s_order": 1,
              "layout": "1",
              "is_deleted": false,
              "template": null,
              "elements": [
                {
                  "id": 144,
                  "block_id": 181,
                  "template_id": 45,
                  "content": null,
                  "created_at": "2020-12-02 15:37:32",
                  "updated_at": "2020-12-02 15:37:32",
                  "type": "slider",
                  "images": [
                    {
                      "id": 69,
                      "entity": "slider",
                      "entity_id": 144,
                      "template_id": null,
                      "url_original": "/img/uploads/1-1606912652.jpg",
                      "url_medium": "/img/uploads/1-1606912652.jpg",
                      "url_small": "/img/uploads/1-1606912652.jpg",
                      "order": 1,
                      "created_at": "2020-12-02 15:37:32",
                      "updated_at": "2020-12-02 15:37:32",
                      "image_url": "http://ycms-client.loc/img/uploads/1-1606912652.jpg"
                    },
                    {
                      "id": 70,
                      "entity": "slider",
                      "entity_id": 144,
                      "template_id": null,
                      "url_original": "/img/uploads/2-1606912652.jpg",
                      "url_medium": "/img/uploads/2-1606912652.jpg",
                      "url_small": "/img/uploads/2-1606912652.jpg",
                      "order": 2,
                      "created_at": "2020-12-02 15:37:32",
                      "updated_at": "2020-12-02 15:37:32",
                      "image_url": "http://ycms-client.loc/img/uploads/2-1606912652.jpg"
                    },
                    {
                      "id": 71,
                      "entity": "slider",
                      "entity_id": 144,
                      "template_id": null,
                      "url_original": "/img/uploads/istockphoto-1166684037-170667a-1606912652.jpg",
                      "url_medium": "/img/uploads/istockphoto-1166684037-170667a-1606912652.jpg",
                      "url_small": "/img/uploads/istockphoto-1166684037-170667a-1606912652.jpg",
                      "order": 3,
                      "created_at": "2020-12-02 15:37:32",
                      "updated_at": "2020-12-02 15:37:32",
                      "image_url": "http://ycms-client.loc/img/uploads/istockphoto-1166684037-170667a-1606912652.jpg"
                    },
                    {
                      "id": 72,
                      "entity": "slider",
                      "entity_id": 144,
                      "template_id": null,
                      "url_original": "/img/uploads/istockphoto-1188086456-170667a-1606912652.jpg",
                      "url_medium": "/img/uploads/istockphoto-1188086456-170667a-1606912652.jpg",
                      "url_small": "/img/uploads/istockphoto-1188086456-170667a-1606912652.jpg",
                      "order": 4,
                      "created_at": "2020-12-02 15:37:32",
                      "updated_at": "2020-12-02 15:37:32",
                      "image_url": "http://ycms-client.loc/img/uploads/istockphoto-1188086456-170667a-1606912652.jpg"
                    }
                  ],
                  "template": {
                    "id": 45,
                    "app_id": 2,
                    "name": "slider template",
                    "margin": "0px",
                    "padding": "0px",
                    "created_at": "2020-11-17 12:10:52",
                    "updated_at": "2020-11-26 21:21:42",
                    "border_width": "2px",
                    "height": "170px",
                    "width": "300px",
                    "color": "#ce2c2c",
                    "bg_color": "#ffffff",
                    "border_type": "dashed",
                    "border_color": "#14bd3e",
                    "border_radius": null,
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": null,
                    "style": "margin: 0px;padding: 0px;border-width: 2px;border-style: dashed;border-color: #14bd3e;height: 170px;color: #ce2c2c;background-color: #ffffff;overflow:auto;text-align:left;"
                  }
                }
              ]
            }
          ]
        },
        {
          "id": 13,
          "app_id": 2,
          "template_id": null,
          "title": "Home",
          "thumb": null,
          "short_content": null,
          "is_active": true,
          "created_at": "2020-12-02 15:51:58",
          "updated_at": "2020-12-02 15:51:58",
          "active_blocks": [
            {
              "id": 182,
              "page_id": 13,
              "template_id": null,
              "order": 1,
              "is_active": true,
              "created_at": "2020-12-02 15:52:28",
              "updated_at": "2020-12-02 15:52:28",
              "s_order": 1,
              "layout": "1-4",
              "is_deleted": false,
              "template": null,
              "elements": []
            },
            {
              "id": 183,
              "page_id": 13,
              "template_id": null,
              "order": 1,
              "is_active": true,
              "created_at": "2020-12-02 15:52:28",
              "updated_at": "2020-12-02 15:52:28",
              "s_order": 2,
              "layout": "3-4",
              "is_deleted": false,
              "template": null,
              "elements": [
                {
                  "id": 145,
                  "block_id": 183,
                  "template_id": 25,
                  "content": "{\"address\":\"Tlendiev Street 231, Алматы, Казахстан\",\"lat\":43.2341108,\"lng\":76.87624799999999}",
                  "created_at": "2020-12-02 15:53:35",
                  "updated_at": "2020-12-02 15:53:35",
                  "type": "map",
                  "images": [],
                  "template": {
                    "id": 25,
                    "app_id": 2,
                    "name": "map template",
                    "margin": "0px",
                    "padding": "0px",
                    "created_at": "2020-10-09 08:16:25",
                    "updated_at": "2020-11-26 22:34:06",
                    "border_width": "1px solid pink",
                    "height": "150px",
                    "width": "200px",
                    "color": "black",
                    "bg_color": "white",
                    "border_type": null,
                    "border_color": null,
                    "border_radius": null,
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": "right",
                    "style": "margin: 0px;padding: 0px;border-width: 1px solid pink;height: 150px;color: black;background-color: white;overflow:auto;text-align: right;"
                  }
                }
              ]
            },
            {
              "id": 184,
              "page_id": 13,
              "template_id": null,
              "order": 2,
              "is_active": true,
              "created_at": "2020-12-02 15:52:34",
              "updated_at": "2020-12-02 15:52:34",
              "s_order": 1,
              "layout": "4",
              "is_deleted": false,
              "template": null,
              "elements": []
            },
            {
              "id": 185,
              "page_id": 13,
              "template_id": null,
              "order": 2,
              "is_active": true,
              "created_at": "2020-12-02 15:52:34",
              "updated_at": "2020-12-02 15:52:34",
              "s_order": 2,
              "layout": "4",
              "is_deleted": false,
              "template": null,
              "elements": []
            },
            {
              "id": 186,
              "page_id": 13,
              "template_id": null,
              "order": 2,
              "is_active": true,
              "created_at": "2020-12-02 15:52:34",
              "updated_at": "2020-12-02 15:52:34",
              "s_order": 3,
              "layout": "4",
              "is_deleted": false,
              "template": null,
              "elements": []
            },
            {
              "id": 187,
              "page_id": 13,
              "template_id": null,
              "order": 2,
              "is_active": true,
              "created_at": "2020-12-02 15:52:34",
              "updated_at": "2020-12-02 15:52:34",
              "s_order": 4,
              "layout": "4",
              "is_deleted": false,
              "template": null,
              "elements": []
            },
            {
              "id": 188,
              "page_id": 13,
              "template_id": null,
              "order": 3,
              "is_active": true,
              "created_at": "2020-12-02 15:52:40",
              "updated_at": "2020-12-02 15:52:40",
              "s_order": 1,
              "layout": "1",
              "is_deleted": false,
              "template": null,
              "elements": [
                {
                  "id": 146,
                  "block_id": 188,
                  "template_id": 45,
                  "content": null,
                  "created_at": "2020-12-02 15:54:09",
                  "updated_at": "2020-12-02 15:54:09",
                  "type": "slider",
                  "images": [
                    {
                      "id": 73,
                      "entity": "slider",
                      "entity_id": 146,
                      "template_id": null,
                      "url_original": "/img/uploads/Capture - Copy-1606913649.PNG",
                      "url_medium": "/img/uploads/Capture - Copy-1606913649.PNG",
                      "url_small": "/img/uploads/Capture - Copy-1606913649.PNG",
                      "order": 1,
                      "created_at": "2020-12-02 15:54:09",
                      "updated_at": "2020-12-02 15:54:09",
                      "image_url": "http://ycms-client.loc/img/uploads/Capture - Copy-1606913649.PNG"
                    },
                    {
                      "id": 75,
                      "entity": "slider",
                      "entity_id": 146,
                      "template_id": null,
                      "url_original": "/img/uploads/w - Copy-1606913649.PNG",
                      "url_medium": "/img/uploads/w - Copy-1606913649.PNG",
                      "url_small": "/img/uploads/w - Copy-1606913649.PNG",
                      "order": 3,
                      "created_at": "2020-12-02 15:54:09",
                      "updated_at": "2020-12-02 15:54:09",
                      "image_url": "http://ycms-client.loc/img/uploads/w - Copy-1606913649.PNG"
                    },
                    {
                      "id": 76,
                      "entity": "slider",
                      "entity_id": 146,
                      "template_id": null,
                      "url_original": "/img/uploads/w-1606913649.PNG",
                      "url_medium": "/img/uploads/w-1606913649.PNG",
                      "url_small": "/img/uploads/w-1606913649.PNG",
                      "order": 4,
                      "created_at": "2020-12-02 15:54:09",
                      "updated_at": "2020-12-02 15:54:09",
                      "image_url": "http://ycms-client.loc/img/uploads/w-1606913649.PNG"
                    }
                  ],
                  "template": {
                    "id": 45,
                    "app_id": 2,
                    "name": "slider template",
                    "margin": "0px",
                    "padding": "0px",
                    "created_at": "2020-11-17 12:10:52",
                    "updated_at": "2020-11-26 21:21:42",
                    "border_width": "2px",
                    "height": "170px",
                    "width": "300px",
                    "color": "#ce2c2c",
                    "bg_color": "#ffffff",
                    "border_type": "dashed",
                    "border_color": "#14bd3e",
                    "border_radius": null,
                    "text_shadow": null,
                    "box_shadow": null,
                    "overflow": null,
                    "text_align": null,
                    "style": "margin: 0px;padding: 0px;border-width: 2px;border-style: dashed;border-color: #14bd3e;height: 170px;color: #ce2c2c;background-color: #ffffff;overflow:auto;text-align:left;"
                  }
                }
              ]
            }
          ]
        }
      ];

    }

  },
  mounted(){
  }

}

</script>

<style lang="scss" scoped>


</style>

